INSERT INTO pokedex.attack
VALUES
-- NAME , TYPE , DAMAGE
	("Absorb", "Grass", 20),
    ("Acid", "Poison", 40),
    ("Acid Armor", "Poison", 0),
    ("Agility", "Psychic", 0),
    ("Amnesia", "Psychic", 0),
    ("Aurora Beam", "Ice", 65),
    ("Barrage", "Normal", 15),
    ("Bide", "Normal", 10),
    ("Bind", "Normal", 15),
    ("Bite", "Dark", 60),
    ("Blizzard", "Ice", 110),
    ("Body Slam", "Normal", 85),
    ("Bone Club", "Ground", 65),
    ("Bonemerang", "Ground", 50),
    ("Bubble", "Ground", 50),
    ("Bubble Beam", "Water", 65),
    ("Clamp", "Water", 35),
    ("Comet Punch", "Normal", 18),
    ("Confuse Ray", "Ghost", 0),
    ("Confusion", "Psychic", 50),
    ("Constrict", "Normal", 10),
    ("Conversion", "Normal", 0),
    ("Crabhammer", "Water", 100),
    ("Cut", "Normal", 50),
    ("Defense Curl", "Normal", 0),
    ("Dig", "Ground", 80),
    ("Disable", "Normal", 0),
    ("Dizzy Punch", "Normal", 70),
    ("Double Kick", "Fighting", 30),
    ("Double Slap", "Normal", 15),
    ("Double Team", "Normal", 0),
    ("Double-Edge", "Normal", 120),
    ("Dragon Rage", "Dragon", 0),
    ("Dream Eater", "Psychic", 100),
    ("Drill Peck", "Flying", 80),
    ("Earthquake", "Ground", 100),
    ("Egg Bomb", "Normal", 100),
    ("Ember", "Fire", 40),
    ("Explosion", "Normal", 250),
    ("Fire Blast", "Fire", 110),
    ("Fire Punch", "Fire", 75),
    ("Fire Spin", "Fire", 35),
    ("Fissure", "Ground", 0),
    ("Flamethrower", "Fire", 90),
    ("Flash", "Normal", 0),
    ("Fly", "Flying", 90),
    ("Focus Energy", "Normal", 0),
    ("Fury Attack", "Normal", 15),
    ("Fury Swipes", "Normal", 18),
    ("Glare", "Normal", 0),
    ("Growl", "Normal", 0),
    ("Guillotine", "Normal", 0),
    ("Gust", "Flying", 40),
    ("Harden", "Normal", 0),
    ("Haze", "Ice", 0),
    ("Headbutt", "Normal", 70),
    ("High Jump Kick", "Fighting", 130),
    ("Horn Attack", "Normal", 65),
    ("Horn Drill", "Normal", 0),
    ("Hydro Pump", "Water", 110),
    ("Hyper Beam", "Normal", 150),
    ("Hyper Fang", "Normal", 80),
    ("Hypnosis", "Psychic", 0),
    ("Ice Beam", "Ice", 90),
    ("Ice Punch", "Ice", 75),
    ("Jump Kick", "Fighting", 100),
    ("Karate Chop", "Fighting", 50),
    ("Kinesis", "Psychic", 0),
    ("Leech Life", "Bug", 80),
    ("Leech Seed", "Grass", 0),
    ("Leer", "Normal", 0),
    ("Lick", "Ghost", 30),
    ("Light Screen", "Psychic", 0),
    ("Lovely Kiss", "Normal", 0),
    ("Low Kick", "Fighting", 0),
    ("Meditate", "Psychic", 0),
    ("Mega Drain", "Grass", 40),
    ("Mega Kick", "Normal", 120),
    ("Mega Punch", "Normal", 80),
    ("Metronome", "Normal", 0),
    ("Mimic", "Normal", 0),
    ("Minimize", "Normal", 0),
    ("Mirror Move", "Flying", 0),
    ("Mist", "Ice", 0),
    ("Night Shade", "Ghost", 0),
    ("Pay Day", "Normal", 40),
    ("Peck", "Flying", 35),
    ("Petal Dance", "Grass", 120),
    ("Pin Missile", "Bug", 25),
    ("Poison Gas", "Poison", 0),
    ("Poison Powder", "Poison", 0),
    ("Poison Sting", "Poison", 15),
    ("Pound", "Normal", 40),
    ("Psybeam", "Psychic", 65),
    ("Psychic", "Psychic", 90),
    ("Psywave", "Psychic", 0),
    ("Quick Attack", "Normal", 40),
    ("Rage", "Normal", 20),
    ("Razor Leaf", "Grass", 55),
    ("Razor Wind", "Normal", 80),
    ("Recover", "Normal", 0),
    ("Reflect", "Psychic", 0),
    ("Rest", "Psychic", 0),
    ("Roar", "Normal", 0),
    ("Rock Slide", "Rock", 75),
    ("Rock Throw", "Rock", 50),
    ("Rolling Kick", "Fighting", 60),
    ("Sand Attack", "Ground", 0),
    ("Scratch", "Normal", 40),
    ("Screech","Normal", 0),
    ("Seismic Toss", "Fighting", 0),
    ("Self-Destruct", "Normal", 200),
    ("Sharpen", "Normal", 0),
    ("Sing", "Normal", 0),
    ("Skull Bash", "Normal", 130),
    ("Slam", "Normal", 80),
    ("Slash", "Normal", 70),
    ("Sleep Powder", "Grass", 0),
    ("Sludge", "Poison", 65),
    ("Smog", "Poison", 30),
    ("Smokescreen", "Normal", 0),
    ("Soft-Boiled", "Normal", 0),
    ("Solar Beam", "Grass", 120),
    ("Sonic Boom", "Normal", 0),
    ("Spike Cannon", "Normal", 20),
    ("Splash", "Normal", 0),
    ("Spore", "Grass", 0),
    ("Stomp", "Normal", 65),
    ("Strength", "Normal", 80),
    ("String Shot", "Bug", 0),
    ("Struggle", "Normal", 50),
    ("Stun Spore", "Grass", 0),
    ("Submission", "Fighting",80),
    ("Substitute", "Normal", 0),
    ("Super Fang", "Normal", 0),
    ("Supersonic", "Normal", 0),
    ("Surf", "Water", 90),
    ("Swift", "Normal", 60),
    ("Swords Dance", "Normal", 0),
    ("Tackle", "Normal", 40),
    ("Tail Whip", "Normal", 0),
    ("Take Down", "Normal", 90),
    ("Teleport", "Psychic", 0),
    ("Thrash", "Normal", 120),
    ("Thunder", "Electric", 110),
    ("Thunder Punch", "Electric", 75),
    ("Thunder Shock", "Electric", 40),
    ("Thunder Wave", "Electric", 0),
    ("Thunderbolt", "Electric", 90),
    ("Toxic", "Poison", 0),
    ("Transform", "Normal", 0),
    ("Tri Attack", "Normal", 80),
    ("Twineedle", "Bug", 25),
    ("Vice Grip", "Normal", 55),
    ("Vine Whip", "Grass", 45),
    ("Water Gun", "Water", 40),
    ("Waterfall", "Water", 80),
    ("Whirlwind", "Normal", 0),
    ("Wing Attack", "Flying", 60),
    ("Withdraw", "Water", 0),
    ("Wrap", "Normal", 15);
    