INSERT INTO pokedex.moveset
VALUES
	(1, "Tackle" , "Growl"),
    (2, "Vine Whip", "Leech Seed"),
    (3, "Poison Gas", "Petal Dance"),
    (4, "Ember", "Growl"),
    (5, "Fire Spin", "Dragon Rage"),
    (6, "Flamethrower", "Slash"),
    (7, "Tackle", "Tail Whip"),
    (8, "Water Gun", "Bubble Beam"),
    (9, "Hydro Pump", "Headbutt"),
    (10,"Strength", "Tackle"),
    (11, "Sharpen", "Stun Spore"),
    (12, "Poison Powder", "Stun Spore"),
    (13, "Bite", "Poison Sting"),
    (14, "Harden", "Harden"),
    (15, "Poison Sting", "Agility"),
    (16, "Tackle","Sand Attack"),
    (17, "Wing Attack", "Quick Attack"),
    (18, "Razor Wind", "Absorb"),
    (19, "Tail Whip", "Quick Attack"),
    (20, "Hyper Fang","Fury Swipes"),
    (21, "Peck","Growl"),
    (22, "Drill Peck", "Agility"),
    (23, "Poison Sting", "Wrap"),
    (24, "Toxic", "Slam"),
    (25, "Thunder Shock", "Quick Attack"),
    (26, "Thunder", "Slam"),
    (27, "Defense Curl", "Scratch"),
    (28, "Slash", "Earthquake"),
    (29, "Peck", "Focus Energy"),
    (30, "Horn Attack", "Toxic"),
    (31, "Poison Sting", "Horn Drill"),
    (32, "Poison Sting", "Tail Whip"),
    (33, "Bite", "Toxic"),
    (34, "Bite", "Super Fang"),
    (35, "Pound", "Defense Curl"),
    (36, "Night Shade", "Body Slam"),
    (37, "Tackle", "Ember"),
    (38, "Hypnosis", "Ice Punch"),
    (39, "Sing", "Pound"),
    (40, "Mimic", "Body Slam"),
    (41, "Absorb", "Supersonic"),
    (42, "Confuse Ray", "Haze"),
    (43, "Absorb", "Acid"),
    (44, "Stun Spore", "Sleep Powder"),
    (45, "Mega Drain", "Toxic"),
    (46, "Scratch", "Sleep Powder"),
    (47, "Growl", "Fury Swipes"),
    (48, "Disable", "Supersonic"),
    (49, "Sleep Powder", "Leech Life"),
    (50, "Scratch", "Sand Attack"),
    (52, "Bite", "Fissure"),
    (53, "Screech", "Slash"),
    (54, "Scratch", "Tail Whip"),
    (55, "Surf", "Amnesia"),
    (56, "Scratch", "Karate Chop"),
    (57, "Thrash", "Rage"),
    (58, "Bite", "Roar"),
    (59, "Cut", "Fire Punch"),
    (60, "Pound", "Hypnosis"),
    (61, "Double Slap", "Bubble Beam"),
    (62, "Hydro Pump", "Body Slam"),
    (63, "Teleport", "Rock Throw"),
    (64, "Confusion", "Night Shade"),
    (65, "Psychic", "Recover"),
    (66, "Focus Energy", "Low Kick"),
    (67, "Seismic Toss", "Karate Chop"),
    (68, "Blizzard", "Super Fang"),
    (69, "Vine Whip", "Glare"),
    (70, "Sleep Powder", "Poison Powder"),
    (71, "Razor Leaf", "Slam"),
    (72, "Poison Sting", "Constrict"),  
    (73, "Bubble Beam", "Surf"),
    (74, "Tackle", "Sand Attack"),
    (75, "Rock Throw", "Self-Destruct"),
    (76, "Earthquake", "Explosion"),
    (77, "Growl", "Tackle"),
    (78, "Fire Blast", "Take Down"),
    (79, "Tackle", "Sleep Powder"),
    (80, "Surf", "Rest"),
    (81, "Thunder Shock", "Thunder Wave"),
    (82, "Thunderbolt", "Thunder"),
    (83, "Cut", "Razor Leaf"),
    (84, "Tri Attack", "Quick Attack"),
    (85, "Agility", "Drill Peck"),
    (86, "Headbutt", "Ember"),
    (87, "Waterfall", "Ice Beam"),
    (88, "Poison Powder", "Pound"),
    (89, "Toxic", "Acid"),
    (90, "Water Gun", "Tackle"),
    (91, "Ice Beam", "Scratch"),
    (92, "Lick", "Smog"),
    (93, "Night Shade", "Toxic"),
    (94, "Dizzy Punch", "Dream Eater"),
    (95, "Rock Throw", "Harden"),
    (96, "Pound", "Disable"),
    (97, "Psybeam", "Meditate"),
    (98, "Bubble", "Vice Grip"),
    (99, "Stomp", "Pay Day"),
    (100, "Sonic Boom", "Swift"),
    (101, "Thunderbolt", "Explosion"),
    (102, "Barrage", "Confusion"),
    (103, "Stun Spore", "Solar Beam"),
    (104, "Growl", "Stun Spore"),
    (105, "Thrash", "Focus Energy"),
    (106, "Rolling Kick", "Double Kick"),
    (107, "Mega Kick", "Jump Kick"),
    (108, "Lick", "Wrap"),
    (109, "Poison Gas", "Stun Spore"),
    (110, "Sludge", "Toxic"),
    (111, "Horn Attack", "Stomp"),
    (112, "Drill Peck", "Rock Slide"),
    (113, "Pound", "Defense Curl"),
    (114, "Absorb", "Constrict"),
    (115, "Comet Punch", "Bite"),
    (116, "Bubble", "Water Gun"),
    (117, "Bubble Beam", "Waterfall"),
    (118, "Peck", "Supersonic"),
    (119, "Quick Attack", "Tail Whip"),
    (120, "Tackle", "Psybeam"),
    (121, "Hydro Pump", "Recover"),
    (122, "Confusion", "Light Screen"),
    (123, "Leer", "Quick Attack"),
    (124, "Pound", "Kinesis"),
    (125, "Thunder Shock", "Quick Attack"),
    (126, "Ember", "Leer"),
    (127, "Bind", "Seismic Toss"),
    (128, "Quick Attack", "Horn Attack"),
    (129, "Splash", "Tackle"),
    (130, "Hydro Pump", "Hyper Beam"),
    (131, "Water Gun", "Mist"),
    (132, "Thrash", "Recover"),
    (133, "Tackle", "Tail Whip"),
    (134, "Aurora Beam", "Hydro Pump"),
    (135, "Thunder", "Haze"),
    (136, "Fire Spin", "Smog"),
    (137, "Tri Attack", "Thunder Wave"),
    (138, "Withdraw", "Water Gun"),
    (139, "Slash", "Supersonic"),
    (140, "Leer", "Sand Attack"),
    (141, "Leech Life", "Rock Slide"),
    (142, "Wing Attack", "Bite"),
    (143, "Rest", "Tackle"),
    (144, "Ice Beam", "Hydro Pump"),
    (145, "Thunder Shock", "Thunder Wave"),
    (146, "Substitute", "Solar Beam"),
    (147, "Thunder Wave", "Rage"),
    (148, "Psychic", "Slam"),
    (149, "Slam", "Hyper Beam"),
    (150, "Confusion", "Psychic"),
    (151, "Thunderbolt","Toxic");
    
    
    
