-- MySQL Script generated by MySQL Workbench
-- Sun 29 Sep 2019 09:24:25 PM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pokedex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pokedex` ;
USE `Pokedex` ;

-- -----------------------------------------------------
-- Table `Pokedex`.`Pokemon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pokedex`.`pokemon` ;

CREATE TABLE IF NOT EXISTS `Pokedex`.`pokemon` (
  `number` INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `hp` INT NULL DEFAULT 0,
  `attack` INT NULL DEFAULT 0,
  `defense` INT NULL DEFAULT 0)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Pokedex`.`Attack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pokedex`.`attack` ;

CREATE TABLE IF NOT EXISTS `Pokedex`.`attack` (
  `name` VARCHAR(45) NOT NULL PRIMARY KEY UNIQUE,
  `type` VARCHAR(45) NULL,
  `damage` VARCHAR(45) NULL)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `Pokedex`.`Moveset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pokedex`.`moveset` ;

CREATE TABLE IF NOT EXISTS `Pokedex`.`moveset` (
  `number` INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
  `primary_attack` VARCHAR(45) NULL,
  `secondary_attack` VARCHAR(45) NULL,
  CONSTRAINT moveset_fk_pattack
    FOREIGN KEY (primary_attack)
    REFERENCES attack (name),
  CONSTRAINT moveset_fk_sattack
    FOREIGN KEY (secondary_attack)
    REFERENCES attack (name))
ENGINE = InnoDB;





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;