-- MySQL Script generated by MySQL Workbench
-- Sun 29 Sep 2019 09:24:25 PM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Notes 
-- Do we need two tables for moves? It seems like the first move should be within the same data set as the second?

-- I'm pretty confused on the best way to store the types, so I just put something simple together and sent an email to the TA. 
-- I'll let you know when she gets back with me. 
-- Also it doesn't work. :/


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pokedex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pokedex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pokedex` ;
USE `Pokedex` ;

-- -----------------------------------------------------
-- Table `Pokedex`.`Pokemon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pokedex`.`Pokemon` ;

CREATE TABLE IF NOT EXISTS `Pokedex`.`Pokemon` (
  `Number` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `HP` INT NULL DEFAULT 0,
  `Attack` INT NULL DEFAULT 0,
  `Defense` INT NULL DEFAULT 0,
  `Primary_Attack` VARCHAR(45) NULL,
  `Secondary_Attack` VARCHAR(45) NULL,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  UNIQUE INDEX `Number_UNIQUE` (`Number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pokedex`.`Primary_Moves`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pokedex`.`Primary_Moves` ;

CREATE TABLE IF NOT EXISTS `Pokedex`.`Primary_Moves` (
  `Name` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NULL,
  `Damage` INT NULL,
  PRIMARY KEY (`Name`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pokedex`.`Secondary_Moves`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pokedex`.`Secondary_Moves` ;

CREATE TABLE IF NOT EXISTS `Pokedex`.`Secondary_Moves` (
  `Name` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  `Damage` VARCHAR(45) NULL,
  PRIMARY KEY (`Name`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- Check

-- -----------------------------------------------------
-- Table `Pokedex`.`type_matrix`
-- Implementation of simple 
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pokedex`.`type_matrix` ;

CREATE TABLE IF NOT EXISTS `Pokedex`.`type_matrix` (
	`index` INT NOT NULL UNIQUE AUTO_INCREMENT,
	`attack_type` VARCHAR,
	`defense_type` VARCHAR,
	`damage_mod` FLOAT,
	PRIMARY KEY (`index`)
) ENGINE=InnoDB;

-- /Check

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
